
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Action;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class bill extends javax.swing.JInternalFrame {
String Sr_No,Equipment,Company,Price,VAT,Quantity,Amount,Product;
private Action MouseClicked;
    /**
     * Creates new form bill
     */
    
    public bill() {
        initComponents();
        Date now=new Date();
        SimpleDateFormat formatter=new  SimpleDateFormat("dd/MM/yyyy");
        jTextField4.setText(formatter.format(now));
        bill_no();
    }
    
           public void bill_no()
      {
        Connection con;
        Statement stmt;
        ResultSet rs;
        String name;
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/jaanvi","root","admin");
            stmt=(Statement)con.createStatement();
            String Query = "Select MAX(billno) from bill";
            rs = stmt.executeQuery(Query);

            while(rs.next())
            {
             int no=Integer.parseInt(rs.getString(1))+1;             
            
            jTextField2.setText(String.valueOf(no));
            }
          }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Bill Form");

        jLabel1.setText("To M/S:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Bill No:");

        jLabel3.setText("Tin No:");

        jLabel4.setText("Date:");

        jLabel5.setText("GR/RR:");

        jLabel6.setText("Transport:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No", "Equipment", "Company", "Product", "Description", "Price", "VAT", "Quantity", "Amount"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("ADD ITEM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DELETE ITEM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("TOTAL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Total:");

        jLabel8.setText("Total Quantity:");

        jLabel9.setText("Total VAT:");

        jLabel10.setText("Grand Total:");

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });

        jButton5.setText("RESET");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setText("Payment:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit" }));

        jLabel12.setText("Paid:");

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
        });

        jLabel13.setText("Balance:");

        jLabel14.setText("Due:");

        jButton6.setText("UPDATE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel15.setText("Total+Due:");

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jTextField7)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jTextField10)
                                    .addComponent(jTextField11)
                                    .addComponent(jTextField12))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))
                        .addContainerGap(83, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5)))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model;
        model=(DefaultTableModel)
        jTable1.getModel();
        model.addTableModelListener(jTable1);
        model.addRow(new Object[] {Sr_No,Equipment,Company,Price,VAT,Quantity,Amount});
  
         int a=jTable1.getRowCount();
         int c=a-1;
         Object b=(Object) jTable1.getRowCount();
         model.setValueAt(b, c, 0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           int[] selectedRowIndices = jTable1.getSelectedRows(); 
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
            int countRemoved = 0; 

            for (int selectedRowIndex : selectedRowIndices)
            { 
             int removeIndex = selectedRowIndex - countRemoved;
             model.removeRow(removeIndex); 
             countRemoved++; 
            
             for(int i=0; i<=model.getRowCount();i++)
             { 
                 model.setValueAt(i+1, i, 0);
             }
            } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
        DefaultTableModel model;
        model = (DefaultTableModel)jTable1.getModel();
        model.addTableModelListener(jTable1);
        //combobox in table
        TableColumn nm=jTable1.getColumnModel().getColumn(1);
        JComboBox ComboBox=new JComboBox();
        nm.setCellEditor(new DefaultCellEditor(ComboBox));
        ComboBox.setVisible(true);
        ComboBox.setAction(MouseClicked);
        ComboBox.addItem("gasstove");
        ComboBox.addItem("pipe");
        ComboBox.addItem("uniform");
        ComboBox.addItem("book");
        ComboBox.addItem("stationery");
        TableColumn nm1=jTable1.getColumnModel().getColumn(2);
        JComboBox ComboBox1=new JComboBox();
        nm1.setCellEditor(new DefaultCellEditor(ComboBox1));
        ComboBox1.setVisible(true);
        ComboBox1.setAction(MouseClicked);
       ComboBox1.removeAllItems();
          TableColumn nm2=jTable1.getColumnModel().getColumn(3);
        JComboBox ComboBox2=new JComboBox();
        nm2.setCellEditor(new DefaultCellEditor(ComboBox2));
        ComboBox2.setVisible(true);
        ComboBox2.setAction(MouseClicked);
         TableColumn nm3=jTable1.getColumnModel().getColumn(4);
        JComboBox ComboBox3=new JComboBox();
        nm3.setCellEditor(new DefaultCellEditor(ComboBox3));
        ComboBox3.setVisible(true);
        ComboBox3.setAction(MouseClicked);
        Connection con;
        Statement s,st2,s1,st1;
        ResultSet rs,rs1,rs2,v;
        String description;
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jaanvi","root","admin");
            s=con.createStatement();
            st2=con.createStatement();
             s1=con.createStatement();
             st1=con.createStatement();
             System.out.println("1");
             int i = jTable1.getSelectedRow();
            if(jTable1.getValueAt(i,1).equals("gasstove"))
            {    
            String Query = "Select distinct(company) from gasstove";
            rs = s.executeQuery(Query);
            System.out.println("2");
            while(rs.next())
            {
                System.out.println("3");
                ComboBox1.addItem(rs.getString("company"));
            }               
            
             
            for(int j=0;j<jTable1.getRowCount();j++)
            {   
                ComboBox2.removeAllItems();
                String X= (String)jTable1.getValueAt(i, 2);
              String Query1 = "select distinct(product) from gasstove where company like '"+X+"' ";
              rs = st1.executeQuery(Query1);
            while(rs.next())
            {
                 ComboBox2.addItem(rs.getString("product"));
            }
              ComboBox3.removeAllItems();
            String Query2 = "select distinct(burner) from gasstove where company like '"+X+"' ";
            rs = st1.executeQuery(Query2);
            while(rs.next())
            {
                 ComboBox3.addItem(rs.getString("burner"));
            }
            
            String Query3 = "select price,tax from gasstove where company like '"+X+"'&& product like '"+jTable1.getValueAt(j,3)+"'&& burner like'"+jTable1.getValueAt(j,4)+"'";
              rs = st1.executeQuery(Query3);
            while(rs.next())
            {
                 jTable1.setValueAt(rs.getString("price"),j,5);
                jTable1.setValueAt(rs.getString("tax"),j,6);
            }
            
           }
           }
            else if(jTable1.getValueAt(i,1).equals("pipe")) 
              {
            String Query = "Select distinct(company) from pipe";
            rs = s.executeQuery(Query);
            System.out.println("2");
            while(rs.next())
            {
                System.out.println("3");
                ComboBox1.addItem(rs.getString("company"));
            }
             
            for(int j=0;j<jTable1.getRowCount();j++)
            {
                ComboBox3.removeAllItems();
             String X= (String)jTable1.getValueAt(j, 2);
                        
              String Query1 = "select distinct(size) from pipe where company like '"+X+"' ";
              rs = st1.executeQuery(Query1);
                        
            while(rs.next())
            {
                 jTable1.setValueAt("Nill", j, 3);
                 ComboBox3.addItem(rs.getString("size"));
            }
              
            String Query2 = "select price,tax from pipe where company like '"+X+"'&& size like '"+jTable1.getValueAt(j,4)+"'";
              rs = st1.executeQuery(Query2);
            while(rs.next())
            {
                 jTable1.setValueAt(rs.getString("price"),j,5);
                jTable1.setValueAt(rs.getString("tax"),j,6);
            }
            }
              }
            else if(jTable1.getValueAt(i,1).equals("uniform")) 
              {
                String Query = "Select distinct(company) from uniform";
            rs = s.executeQuery(Query);
            System.out.println("2");
            while(rs.next())
            {
                System.out.println("3");
                ComboBox1.addItem(rs.getString("company"));
            }
             
            for(int j=0;j<jTable1.getRowCount();j++)
            {
                ComboBox3.removeAllItems();
             String X= (String)jTable1.getValueAt(j, 2);
              String Query1 = "select distinct(colour) from uniform where company like '"+X+"' ";
              rs = st1.executeQuery(Query1);
            while(rs.next())
            {
                 jTable1.setValueAt("Nill", j, 3);
                 ComboBox3.addItem(rs.getString("colour"));
            }
              
            String Query2 = "select price,tax from uniform where company like '"+X+"'&& colour like '"+jTable1.getValueAt(j,4)+"'";
              rs = st1.executeQuery(Query2);
                        

              while(rs.next())
            {
                 jTable1.setValueAt(rs.getString("price"),j,5);
                jTable1.setValueAt(rs.getString("tax"),j,6);
            }
            
           }  
              }
            
            else if(jTable1.getValueAt(i,1).equals("book")) 
              {
                String Query = "Select distinct(company) from book";
            rs = s.executeQuery(Query);
            System.out.println("2");
            while(rs.next())
            {
                System.out.println("3");
                ComboBox1.addItem(rs.getString("company"));
            }
             
            for(int j=0;j<jTable1.getRowCount();j++)
            {
                ComboBox3.removeAllItems();
             String X= (String)jTable1.getValueAt(j, 2);
              String Query1 = "select distinct(colour) from book where company like '"+X+"' ";
              rs = st1.executeQuery(Query1);
            while(rs.next())
            {
      jTable1.setValueAt("Nill", j, 3);
                ComboBox3.addItem(rs.getString("colour"));
            }
              
            String Query2 = "select price,tax from book where company like '"+X+"'&& colour like '"+jTable1.getValueAt(j,4)+"'";
              rs = st1.executeQuery(Query2);
                        
            while(rs.next())
            {
                 jTable1.setValueAt(rs.getString("price"),j,5);
                jTable1.setValueAt(rs.getString("tax"),j,6);
            }
            
           }  
         }
                else if(jTable1.getValueAt(i,1).equals("stationery")) 
              {
                String Query = "Select distinct(company) from stationery";
            rs = s.executeQuery(Query);
            System.out.println("2");
            while(rs.next())
            {
                System.out.println("3");
                ComboBox1.addItem(rs.getString("company"));
            }
             
            for(int j=0;j<jTable1.getRowCount();j++)
            {
                ComboBox3.removeAllItems();
             String X= (String)jTable1.getValueAt(j, 2);
              String Query1 = "select distinct(description) from stationery where company like '"+X+"' ";
              rs = st1.executeQuery(Query1);
            while(rs.next())
            {
                 jTable1.setValueAt("Nill", j, 3);
                 ComboBox3.addItem(rs.getString("description"));
            }
              
            String Query2 = "select price,tax from stationery where company like '"+X+"'&& description like '"+jTable1.getValueAt(j,4)+"'";
              rs = st1.executeQuery(Query2);
                        

              while(rs.next())
            {
                 jTable1.setValueAt(rs.getString("price"),j,5);
                jTable1.setValueAt(rs.getString("tax"),j,6);
            }
            
           }  
              }
        
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        Connection con;
        Statement s;
        ResultSet rs;
        try
        {   
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jaanvi","root","admin");
            s=con.createStatement();
            int i = jTable1.getSelectedRow();
             if(jTable1.getValueAt(i,1).equals("gasstove"))
             {
              String Query="select quantity from gasstove where company like '"+jTable1.getValueAt(i,2)+"'&& product like '"+jTable1.getValueAt(i,3)+"'&& burner like'"+jTable1.getValueAt(i,4)+"'";
              rs = s.executeQuery(Query);
              if(rs.next()==true)
              {
                  double quantity=Double.parseDouble((String)rs.getString("quantity"));
                  double quantity1=Double.parseDouble((String)jTable1.getValueAt(i,7));
                  String q=rs.getString("quantity");
                  if(q.equals("0")||quantity1>quantity)
                  {
                      JOptionPane.showMessageDialog(this,"Out of stock and quantity="+quantity);
                    
                  }
                 else if(!q.equals("0"))
                  {
                      double quantity3=quantity-quantity1;
                  String Query2="update gasstove set quantity='"+quantity3+"' where company like '"+jTable1.getValueAt(i,2)+"'&& product like '"+jTable1.getValueAt(i,3)+"'&& burner like'"+jTable1.getValueAt(i,4)+"'";
                  s.executeUpdate(Query2);
                  for(int j=0;j<jTable1.getRowCount();j++)
            {
                int a=Integer.parseInt((String) jTable1.getValueAt(j,5));
                int b=Integer.parseInt((String)jTable1.getValueAt(j,7));
                double c=Double.parseDouble((String)jTable1.getValueAt(j,6));
                jTable1.setValueAt(String.valueOf(a*b),j,8);
            }   
       
                  }
                   }
             }
             else if(jTable1.getValueAt(i,1).equals("pipe"))
             {
              String Query="select quantity from pipe where company like '"+jTable1.getValueAt(i,2)+"' && size like'"+jTable1.getValueAt(i,4)+"'";
              rs = s.executeQuery(Query);
              if(rs.next()==true)
              {
                  double quantity=Double.parseDouble((String)rs.getString("quantity"));
                  double quantity1=Double.parseDouble((String)jTable1.getValueAt(i,7));
                  String q=rs.getString("quantity");
                  if(q.equals("0")||quantity1>quantity)
                  {
                      JOptionPane.showMessageDialog(this,"Out of stock and quantity="+quantity);
                  }
                  else if(!q.equals("0"))
                  {
                      double quantity3=quantity-quantity1;
                  String Query2="update pipe set quantity='"+quantity3+"' where company like '"+jTable1.getValueAt(i,2)+"' && size like'"+jTable1.getValueAt(i,4)+"'";
                  s.executeUpdate(Query2);
                  for(int j=0;j<jTable1.getRowCount();j++)
            {
                int a=Integer.parseInt((String) jTable1.getValueAt(j,5));
                int b=Integer.parseInt((String)jTable1.getValueAt(j,7));
                double c=Double.parseDouble((String)jTable1.getValueAt(j,6));
                jTable1.setValueAt(String.valueOf(a*b),j,8);
            }   
       
                  } 
                   }
             }
      else if(jTable1.getValueAt(i,1).equals("book"))
             {
              String Query="select quantity from book where company like '"+jTable1.getValueAt(i,2)+"' && color like'"+jTable1.getValueAt(i,4)+"'";
              rs = s.executeQuery(Query);
              if(rs.next()==true)
              {
                  double quantity=Double.parseDouble((String)rs.getString("quantity"));
                  double quantity1=Double.parseDouble((String)jTable1.getValueAt(i,7));
                  String q=rs.getString("quantity");
                  if(q.equals("0")||quantity1>quantity)
                  {
                     JOptionPane.showMessageDialog(this,"Out of stock and quantity="+quantity);
                  }
                  else if(!q.equals("0"))
                  {
                      double quantity3=quantity-quantity1;
                  String Query2="update book set quantity='"+quantity3+"' where company like '"+jTable1.getValueAt(i,2)+"' && color like'"+jTable1.getValueAt(i,4)+"'";
                  s.executeUpdate(Query2);
                  for(int j=0;j<jTable1.getRowCount();j++)
            {
                int a=Integer.parseInt((String) jTable1.getValueAt(j,5));
                int b=Integer.parseInt((String)jTable1.getValueAt(j,7));
                double c=Double.parseDouble((String)jTable1.getValueAt(j,6));
                jTable1.setValueAt(String.valueOf(a*b),j,8);
            }   
       
                  } 
                   }
             }
                    else if(jTable1.getValueAt(i,1).equals("uniform"))
             {
              String Query="select quantity from uniform where company like '"+jTable1.getValueAt(i,2)+"' && color like'"+jTable1.getValueAt(i,4)+"'";
              rs = s.executeQuery(Query);
              if(rs.next()==true)
              {
                  double quantity=Double.parseDouble((String)rs.getString("quantity"));
                  double quantity1=Double.parseDouble((String)jTable1.getValueAt(i,7));
                  String q=rs.getString("quantity");
                  if(q.equals("0")||quantity1>quantity)
                  {
                      JOptionPane.showMessageDialog(this,"Out of stock and quantity="+quantity);
                  }
                  else if(!q.equals("0"))
                  {
                      double quantity3=quantity-quantity1;
                  String Query2="update uniform set quantity='"+quantity3+"' where company like '"+jTable1.getValueAt(i,2)+"' && color like'"+jTable1.getValueAt(i,4)+"'";
                  s.executeUpdate(Query2);
                  for(int j=0;j<jTable1.getRowCount();j++)
            {
                int a=Integer.parseInt((String) jTable1.getValueAt(j,5));
                int b=Integer.parseInt((String)jTable1.getValueAt(j,7));
                double c=Double.parseDouble((String)jTable1.getValueAt(j,6));
                jTable1.setValueAt(String.valueOf(a*b),j,8);
            }   
       
                  } 
                   }
             }
                      else if(jTable1.getValueAt(i,1).equals("stationery"))
             {
              String Query="select quantity from stationery where company like '"+jTable1.getValueAt(i,2)+"' && description like'"+jTable1.getValueAt(i,4)+"'";
              rs = s.executeQuery(Query);
              if(rs.next()==true)
              {
                  double quantity=Double.parseDouble((String)rs.getString("quantity"));
                  double quantity1=Double.parseDouble((String)jTable1.getValueAt(i,7));
                  String q=rs.getString("quantity");
                  if(q.equals("0")||quantity1>quantity)
                  {
                      JOptionPane.showMessageDialog(this,"Out of stock and quantity="+quantity);
                  }
                  else if(!q.equals("0"))
                  {
                      double quantity3=quantity-quantity1;
                  String Query2="update stationery set quantity='"+quantity3+"' where company like '"+jTable1.getValueAt(i,2)+"' && description like'"+jTable1.getValueAt(i,4)+"'";
                  s.executeUpdate(Query2);
                  for(int j=0;j<jTable1.getRowCount();j++)
            {
                int a=Integer.parseInt((String) jTable1.getValueAt(j,5));
                int b=Integer.parseInt((String)jTable1.getValueAt(j,7));
                double c=Double.parseDouble((String)jTable1.getValueAt(j,6));
                jTable1.setValueAt(String.valueOf(a*b),j,8);
            }   
       
                  } 
                  
                   }
             }
 
             }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         // TODO add your handling code here:
      Connection con;
        Statement s;
        ResultSet rs;
        try
        {   
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jaanvi","root","admin");
            s=con.createStatement();
           double a=0,b=0,g=0;
            for(int j=0;j<jTable1.getColumnCount();j++)
            {
                double c=Double.parseDouble((String)jTable1.getValueAt(j,8));
                 a=a+c;
                 double d=Double.parseDouble((String)jTable1.getValueAt(j,7));
                 b=b+d;
                 double f=Double.parseDouble((String)jTable1.getValueAt(j,6));
                 g=g+f;
                 double t=a*(g/100);
                 jTextField7.setText(String.valueOf(a));
                jTextField8.setText(String.valueOf(b));
                jTextField9.setText(String.valueOf(g));
                jTextField10.setText(String.valueOf(a+t));
                 double total=Double.parseDouble(jTextField10.getText());
            double paid=Double.parseDouble(jTextField13.getText());
            jTextField14.setText(String.valueOf(total+paid));
            }   
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection con;
        Statement s,s1;
        ResultSet vs,rs;
        try
        {   
            int i;
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jaanvi","root","admin");
            s=con.createStatement();
            s1=con.createStatement();
            int row=jTable1.getRowCount();
            for(i=0;i<row;i++)
            {
            String Query="insert into bill(name,billno,tinno,date,gr,transport,srno,equipment,company,product,description,price,vat,quantity,amount,total,totalquantity,totalvat,grandtotal,payment,paid,balance) values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTable1.getValueAt(i,0)+"','"+jTable1.getValueAt(i,1)+"','"+jTable1.getValueAt(i,2)+"','"+jTable1.getValueAt(i,3)+"','"+jTable1.getValueAt(i,4)+"','"+jTable1.getValueAt(i,5)+"','"+jTable1.getValueAt(i,6)+"','"+jTable1.getValueAt(i,7)+"','"+jTable1.getValueAt(i,8)+"','"+jTextField7.getText()+"','"+jTextField8.getText()+"','"+jTextField9.getText()+"','"+jTextField10.getText()+"','"+jComboBox1.getSelectedItem()+"','"+jTextField11.getText()+"','"+jTextField12.getText()+"')";
            s.executeUpdate(Query);
            }
            if(!jTextField12.getText().equals("0.0"))
            {
            String Query1="insert into dues(name,balance,due) values('"+jTextField1.getText()+"','"+jTextField12.getText()+"','"+jTextField13.getText()+"')";
            s1.executeUpdate(Query1);
            }

            JOptionPane.showMessageDialog(this,"Data is Submit");
            }
        catch(Exception e)
        {
            System.out.println(e);
        }
                                          
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        DefaultTableModel model;
        model = (DefaultTableModel)jTable1.getModel();
        model.addTableModelListener(jTable1);
        model.setRowCount(0);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        // TODO add your handling code here:
        if(!jTextField14.getText().equals(""))
        {
        double total=Double.parseDouble(jTextField14.getText());
        double paid=Double.parseDouble(jTextField11.getText());
        jTextField12.setText(String.valueOf(total-paid));
        }
        else
        {
            double total=Double.parseDouble(jTextField10.getText());
        double paid=Double.parseDouble(jTextField11.getText());
        jTextField12.setText(String.valueOf(total-paid));
        }
    }//GEN-LAST:event_jTextField11KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         Connection con;
        Statement s,s1;
        ResultSet vs,rs;
        try
        {   
            int i;
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jaanvi","root","admin");
            s=con.createStatement();
            s1=con.createStatement();
            int row=jTable1.getRowCount();
            for(i=0;i<row;i++)
            {
            String Query="update bill set name='"+jTextField1.getText()+"',tinno='"+jTextField3.getText()+"',date='"+jTextField4.getText()+"',gr='"+jTextField5.getText()+"',transport='"+jTextField6.getText()+"',srno='"+jTable1.getValueAt(i,0)+"',equipment='"+jTable1.getValueAt(i,1)+"',company='"+jTable1.getValueAt(i,2)+"',product='"+jTable1.getValueAt(i,3)+"',description='"+jTable1.getValueAt(i,4)+"',price='"+jTable1.getValueAt(i,5)+"',vat='"+jTable1.getValueAt(i,6)+"',quantity='"+jTable1.getValueAt(i,7)+"',amount='"+jTable1.getValueAt(i,8)+"',total='"+jTextField7.getText()+"',totalquantity='"+jTextField8.getText()+"',totalvat='"+jTextField9.getText()+"',grandtotal='"+jTextField10.getText()+"',payment='"+jComboBox1.getSelectedItem()+"',paid='"+jTextField11.getText()+"',balance='"+jTextField12.getText()+"' where billno='"+jTextField2.getText()+"'";
            s.executeUpdate(Query);
            }
                        JOptionPane.showMessageDialog(this,"Data is Update");
            }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
         Connection con;
        Statement s;
        ResultSet rs;
        try
        {   
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jaanvi","root","admin");
            s=con.createStatement();
            String Query="select balance from dues where name like '"+jTextField1.getText()+"'";
            rs=s.executeQuery(Query);
            while(rs.next())
            {
                jTextField13.setText(rs.getString("balance"));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        
    }//GEN-LAST:event_jTextField10KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
